apiVersion: v1
kind: Service
metadata:
  name: {{ include "presto.fullname" . }}
  labels:
    {{- include "presto.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if hasKey .Values.service "nodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- if .Values.server.resourceManager.enabled }}
    app.kubernetes.io/component: resourceManager
    {{- else }}
    app.kubernetes.io/component: coordinator
    {{- end }}
    {{- include "presto.selectorLabels" . | nindent 4 }}
